### ISSUE TITLE
MPI error in running rocstar

### ISSUE THREAD

**Issue by Dong2hu** [IllinoisRocstar/Rocstar-legacy#10]
When I execute the following script:
`rflupart -c ACM -v 2`
The error message appears as follows:
`*** The MPI_Comm_f2c() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.`

The compiler and software versions I use are:
"-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- The Fortran compiler identification is GNU 4.8.5
-- Found MPI_C: /usr/local/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/local/lib/libmpi.so (found version "3.1") 
-- Found MPI_Fortran: /usr/local/lib/libmpi_usempi.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")"

The openmpi version I installed is 4.0.4, but the version cmake prompts is 3.1. I don't know why

Hope to get help from developers, thank you very much

**Comment by msafdari1234** [comment]
This problem is identified and hardened in our  [modern Rocstar project](https://github.com/IllinoisRocstar/Rocstar). I recommend you switch to our modern Rocstar project. We are not maintaining legacy code anymore. If you insist using legacy project, you maybe able to address this problem if you switch to MPICH.

**Comment by MTCam** [comment]
Try `mpiexec -n 1 rflupart -c ACM -v 2`?

**Comment by gruneisen** [comment]
Additionally, it looks as though perhaps you may have some different versions on MPI on your system and the linker is getting confused? There are some breadcrumbs in this post:

https://stackoverflow.com/questions/31687583/mumps-the-mpi-comm-f2c-function-was-called-before-mpi-init-was-invoked

Perhaps compiling MPI from source and then compiling/linking against your own compiled MPI may help?

**Comment by msafdari1234** [comment]
The problem is caused by `rflupart` utility not properly initializing the MPI environment. The working solution for this problem is to add this code to `rflupart.F90` after the line 167:

```
CALL MPI_Init(errorFlag)
global%error = errorFlag
IF ( global%error /= ERR_NONE ) THEN
  CALL ErrorStop(global,ERR_MPI_OUTPUT,__LINE__)
END IF ! global%error
```

but I should stress, we are not maintaining the legacy project anymore. Please note that several other similar and more complex issues are address in the modern Rocstar project.

**Comment by Dong2hu** [comment]
> The problem is caused by `rflupart` utility not properly initializing the MPI environment. The working solution for this problem is to add this code to `rflupart.F90` after the line 167:
> 
> ```
> CALL MPI_Init(errorFlag)
> global%error = errorFlag
> IF ( global%error /= ERR_NONE ) THEN
>   CALL ErrorStop(global,ERR_MPI_OUTPUT,__LINE__)
> END IF ! global%error
> ```
> 
> but I should stress, we are not maintaining the legacy project anymore. Please note that several other similar and more complex issues are address in the modern Rocstar project.

According to your prompt, the error in running rflupart is solved. When I ran rluinit, the same error was reported, and I also modified rfluinit. Finally, the program runs correctly.
Thank you very much for your help.
I hope to use the latest version of rocstar as soon as possible, but I still need to use some modules, such as rocfrac.
Thank you again for your help
